Repository enki-polvo/polvo-logger, pull requests merged in 2025-05, with the labels that each got.

#5 Feat: define common log model
  logger/logger.go
  logger/objPool.go
  main.go
  model/commonModel.go
  model/entity/model.go
  model/event/model.go
  model/state/model.go
Labels: enhancement

#6 Feat: Define file common model
  model/entity/model.go
  model/event/model.go
  model/state/model.go
Labels: enhancement

#8 Feat: Implement Git hook to enforce commit message conventions
  .githooks/commit-msg
  .githooks/config
  README.md
Labels: documentation

#10 Task: FileEvent Model is not compatible with Sigma file-event rules
  model/event/model.go
Labels: invalid

#11 Feat: Implement event object pool to decrease GC pressure due to repeatedly object memory reallocations
  logger/objPool.go
  model/commonModel.go
  model/entity/model.go
  model/event/model.go
  model/state/model.go
  pool/README.md
  pool/eventPool.go
  pool/eventPool_test.go
Labels: enhancement

#13 Task: Change pool interface
  pool/README.md
  pool/eventPool.go
  pool/eventPool_test.go
Labels: enhancement, invalid

#16 Task: Clarify naming of state model
  model/state/stateConstants.go
Labels: enhancement

#19 Task: Correct ProcessTermiateMetadata.Ret type from int to int64
  model/event/model.go
Labels: bug
