Repository enki-polvo/polvo-logger, pull requests merged in 2025-06, with the labels that each got.

#20 Task: Rename JSON format tags in the polvo-logger's model definition
  model/commonModel.go
  model/event/model.go
Labels: invalid

#28 Feat/25/decode metadata with mapstructure
  go.mod
  go.sum
  model/commonModel.go
  model/commonModel_test.go
  model/event/model.go
Labels: enhancement

#30 Bug/29: Include missing username field for file type events
  .gitignore
  model/event/model.go
Labels: bug

#32 Bug/31: Add missing obj.Metadata field in eventPool.go (#31)
  pool/eventPool.go
Labels: bug

#34 Bug/33: Fix typo in obj.Metadata field in eventPool.go (#33)
  pool/eventPool.go
Labels: bug

#36 bug(model): fix FileOpenEvent Metadata's tag
  model/event/model.go
Labels: bug
